version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: petiko_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=petiko
      - DB_USERNAME=root
      - DB_PASSWORD=root

  frontend:
    build:
      context: ./PerfilUser-FrontEnd/perfil-user-front
      dockerfile: Dockerfile.frontend
    container_name: petiko_frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./PerfilUser-FrontEnd/perfil-user-front:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run serve

  db:
    image: mysql:8.0
    container_name: petiko_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: petiko
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: 